export const data=[
    {  imgUrl:"https://tse3.mm.bing.net/th?id=OIP.WuYEGgz6L82X0Lj2J9GunQHaHa&pid=Api&P=0&w=175&h=175",
        title:"Dark ",
        description:"netflix series",
        bt:"Watch Now",
        rate:5,
        id : 1,
        video:"https://www.youtube.com/embed/U_1XXdXEKgI",
        topic:"Un agent du gouvernement doit traquer et tuer un terroriste avant qu'il ne perde sa mémoire à cause de la démence Réalisation",
      },
      { imgUrl:"https://tse1.mm.bing.net/th?id=OIP.jsSnvX9P6xmwbnuznluM8AHaK-&pid=Api&P=0&w=119&h=177",
        title:"Extra Currucular ",
        description:" netflix series",
        bt:"Watch Now",
        rate:4,
        id : 2,
        video:"https://www.youtube.com/embed/aV_DBz2rKsI",
        topic:"est une série télévisée dramatique criminelle sud-coréenne en 10 épisodes d’entre 44-72 minutes, créée par Jin Han-sae et diffusée le 29 avril 2020 sur la plate-forme Netflix1",
      },
       {imgUrl:"https://tse3.mm.bing.net/th?id=OIP.AvfIrRRX1kkvfvOVCjxXCAHaK-&pid=Api&P=0&w=116&h=171",
        title:"Stranger Things",
        description:" netflix series",
        bt:"Watch Now",
        rate:3,
        id:3,
        video:"https://www.youtube.com/embed/sBEvEcpnG7k",
        topic:"est une série télévisée américaine de science-fiction horrifique, créée par les frères Matt et Ross Duffer et diffusée depuis le 15 juillet 2016 sur Netflix. Elle compte à ce jour quatre saisons et trente-deux épisodes. La seconde partie de la quatrième saison, composée de deux épisodes, sera diffusée le premier juillet 2022. Une cinquième et dernière saison a été annoncée le 17 février 2022.L'ambiance de la série est fortement inspirée par les films fantastiques et de science-fiction des années 1980, puisant ses influences dans les œuvres de H. P. Lovecraft, Steven Spielberg, John Carpenter, John Hughes ou Stephen King2,3.Stranger Things est l'une des séries diffusées en streaming les plus regardées dans le monde4,5,6.",
      },
      { imgUrl:"https://tse3.mm.bing.net/th?id=OIP.1PeEnNKbbOIAAcnpFsqI2AHaEK&pid=Api&P=0&w=327&h=184",
        title:"Vampire Diaries",
        description:" netflix series",
        bt:"Watch Now",
        rate:3,
        id:4,
        video:"https://www.youtube.com/embed/BmVmhjjkN4E",
        topic:"Vampire Diaries, ou Journal d'un vampire au Québec, (The Vampire Diaries) est une série télévisée américaine développée par Kevin Williamson et Julie Plec. Elle a été diffusée du 10 septembre 2009 au 10 mars 2017 sur The CW aux États-Unis et en simultané sur CTV Two au Canada.",
      },
      { imgUrl:"https://tse2.mm.bing.net/th?id=OIP.vIcBMg50Zi3wBeehA-YPRQHaEK&pid=Api&P=0&w=325&h=182",
        title:"My First Love",
        description:" netflix series",
        bt:"Watch Now",
        rate:2,
        id:5,
        video:"https://www.youtube.com/embed/tc9YvtGE16s",
        topic:"est une série télévisée fantastique sud-coréenne de 2018vedette Lee Jung-shin , Seo Ji-hoon et Lee Yul-eum . Il est basé sur le webtoon du même titre, sorti en 2015. Il a été diffuséles lundis et mardis d' OCN à 21h00 ( KST ) du 8 janvier au 6 février 2018 pour dix épisodes. [3] [4] [5]",
      },
     {
        imgUrl:"https://tse4.mm.bing.net/th?id=OIF.XqLgxCeui60YvC7YMmk89Q&pid=Api&P=0&w=169&h=95",
        title:"Squid Game",
        description:" netflix series",
        bt:"Watch Now",
        rate:2,
        id:6,
        video:"https://www.youtube.com/embed/oqxAJKy0ii4",
        topic:"ou Le Jeu du calmar au Québec, est une série télévisée dramatique de survie sud-coréenne de 9 épisodes, créée par Hwang Dong-hyeok et diffusée dans le monde entier le 17 septembre 2021 sur Netflix1.",
      },
]